#pragma once
// 제작자 : 이건주
// 제작일 : 2026-03-04
// 수정일 : 2026-03-05
#include "NativeGameplayTags.h"

namespace MHGameplayTags
{
	// 이동 입력 태그
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move);

	// 시점 입력 태그
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Look);
	
	//Element Tags (속성 태그)
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_Fire);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_Water);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_Thunder);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_Ice);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_Dragon);
	

}
