#pragma once

//손승우 추가: 무기 타입 / 납도 상태 / 전투 상태 전용 네이티브 게임플레이 태그 선언

#include "NativeGameplayTags.h"

namespace MHCombatStateGameplayTags
{
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WeaponType_LongSword);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WeaponType_ChargeBlade);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WeaponSheath_Sheathed);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WeaponSheath_Unsheathing);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WeaponSheath_Unsheathed);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WeaponSheath_Sheathing);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatState_None);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatState_Draw);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatState_Sheathe);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatState_Dodge);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatState_Attack);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatState_SpiritAttack);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatState_Counter);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatState_SpecialSheathe);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatState_Helmbreaker);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatState_Clutch);
}
