#pragma once

#include "NativeGameplayTags.h"

namespace MHGreatSwordGameplayTags
{
    // 발도 / 기본 시작 기술
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_DrawSlash);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_DrawForwardSlash);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_DrawChargeSlash);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_DrawGuard);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_OverheadSlash);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_WideSlash);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_RisingSlash);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_Guard);

    // 모아베기 계열
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_ChargeSlash_Lv0);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_ChargeSlash_Lv1);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_ChargeSlash_Lv2);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_StrongChargeSlash_Lv0);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_StrongChargeSlash_Lv1);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_StrongChargeSlash_Lv2);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_TrueChargeSlash_Lv0);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_TrueChargeSlash_Lv1);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_TrueChargeSlash_Lv2);

    // 파생 기술
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_Tackle);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_JumpingWideSlash);
}
