#pragma once

#include "NativeGameplayTags.h"

namespace MHGreatSwordGameplayTags
{
    // 발도 / 기본 시작 기술
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_DrawOnly);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_DrawForwardSlash);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_DrawDefaultCharge);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_DrawGuard);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_OverheadSlash);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_WideSlash);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_RisingSlash);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_Guard);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_Sheathe);

    // 차징 / 릴리즈 기술
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_ChargeSlashCharging);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_ChargeSlash);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_StrongChargeSlashCharging);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_StrongChargeSlash);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_TrueChargeSlashCharging);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_TrueChargeSlash);

    // 파생 기술
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_Tackle);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_JumpingWideSlash);

    // 구르기 기술
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_RollFront);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_RollBack);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_RollLeft);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_GS_RollRight);
}
