#pragma once

#include "NativeGameplayTags.h"

namespace MHInputPatternGameplayTags
{
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputPattern_LS_DrawOnly);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputPattern_LS_DrawAdvancingSlash);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputPattern_LS_DrawSpiritSlash1);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputPattern_LS_AdvancingSlash);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputPattern_LS_VerticalSlash);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputPattern_LS_RisingSlash);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputPattern_LS_Thrust);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputPattern_LS_Spirit);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputPattern_LS_FadeSlash);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputPattern_LS_LateralFadeSlash);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputPattern_LS_SpiritThrust);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputPattern_LS_ForesightSlash);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputPattern_LS_SpecialSheathe);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputPattern_LS_IaiSlash);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputPattern_LS_IaiSpiritSlash);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputPattern_LS_Helmbreaker);

    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputPattern_GS_DrawOnly);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputPattern_GS_DrawCharge);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputPattern_GS_DrawGuard);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputPattern_GS_Primary);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputPattern_GS_ForwardPrimary);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputPattern_GS_PrimaryRelease);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputPattern_GS_Secondary);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputPattern_GS_WeaponSpecial);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputPattern_GS_WeaponSpecialRelease);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputPattern_GS_Simultaneous);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputPattern_GS_Dodge);
    PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputPattern_GS_AutoRelease);
}
