#pragma once

//손승우 수정: 롱소드 Move 태그를 입력 패턴 설계 기준에 맞게 정렬

#include "NativeGameplayTags.h"

namespace MHLongSwordGameplayTags
{
	// ===== Draw / Entry =====
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_LS_DrawOnly);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_LS_DrawAdvancingSlash);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_LS_DrawSpiritSlash1);
	// ===== End Draw / Entry =====

	// ===== Normal =====
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_LS_AdvancingSlash);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_LS_VerticalSlash);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_LS_Thrust);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_LS_RisingSlash);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_LS_DownwardSlash);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_LS_FadeSlash);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_LS_LateralFadeSlash);
	// ===== End Normal =====

	// ===== Spirit =====
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_LS_SpiritSlash1);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_LS_SpiritSlash2);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_LS_SpiritSlash3);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_LS_SpiritRoundslash);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_LS_SpiritAdvancingSlash);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_LS_SpiritThrust);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_LS_SpiritHelmbreaker);
	// ===== End Spirit =====

	// ===== Special / Counter =====
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_LS_SpecialSheathe);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_LS_IaiSlash);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_LS_IaiSpiritSlash);
	PROJECTMHW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move_LS_ForesightSlash);
	// ===== End Special / Counter =====
}